/**
 * The subtitles of a YouTube video, for a recipe that is only spoken.
 *
 * The watch page lists the video's caption tracks — written by the author,
 * or generated by YouTube's speech recognition — each with an address that
 * returns the text as XML. A recipe read aloud is then a page of text, which
 * a model can turn into ingredients and steps the same way it reads a blog.
 *
 * YouTube does not always hand these out to a server; when it does not, the
 * capture says the recipe is only in the video, as before. Nothing breaks.
 */

export interface CaptionTrack {
    baseUrl: string;
    languageCode: string;
    /** 'asr' for speech recognition; absent for captions somebody wrote. */
    kind?: string;
}

/** Reads the `captionTracks` array out of a watch page, without parsing the megabytes around it. */
export function captionTracksFrom(html: string): CaptionTrack[] {
    const at = html.indexOf('"captionTracks":[');
    if (at === -1) return [];
    const start = html.indexOf('[', at);

    // Walk to the matching bracket, minding strings.
    let depth = 0;
    let inString = false;
    let escaped = false;
    let end = -1;
    for (let index = start; index < html.length && index < start + 50_000; index += 1) {
        const character = html[index];
        if (inString) {
            if (escaped) escaped = false;
            else if (character === '\\') escaped = true;
            else if (character === '"') inString = false;
            continue;
        }
        if (character === '"') inString = true;
        else if (character === '[') depth += 1;
        else if (character === ']') {
            depth -= 1;
            if (depth === 0) {
                end = index;
                break;
            }
        }
    }
    if (end === -1) return [];

    try {
        const tracks = JSON.parse(html.slice(start, end + 1)) as unknown[];
        return tracks.flatMap((track) => {
            const entry = track as Record<string, unknown>;
            return typeof entry.baseUrl === 'string' && typeof entry.languageCode === 'string'
                ? [{ baseUrl: entry.baseUrl, languageCode: entry.languageCode, kind: typeof entry.kind === 'string' ? entry.kind : undefined }]
                : [];
        });
    } catch {
        return [];
    }
}

/**
 * The best track to read: written captions over generated ones, German or
 * English over anything else, and otherwise whatever there is — a model reads
 * Italian too, and the recipe it writes comes back in the cookbook's words.
 */
export function bestCaptionTrack(tracks: CaptionTrack[]): CaptionTrack | null {
    const score = (track: CaptionTrack) =>
        (track.kind === 'asr' ? 0 : 2) + (/^(de|en)/i.test(track.languageCode) ? 1 : 0);
    return [...tracks].sort((a, b) => score(b) - score(a))[0] ?? null;
}

function decodeEntities(text: string): string {
    // Twice: the timed-text XML escapes text that was already escaped.
    let decoded = text;
    for (let round = 0; round < 2; round += 1) {
        decoded = decoded
            .replace(/&#(\d+);/g, (_, code) => String.fromCodePoint(Number(code)))
            .replace(/&#x([\da-f]+);/gi, (_, code) => String.fromCodePoint(Number.parseInt(code, 16)))
            .replace(/&quot;/g, '"')
            .replace(/&#39;|&apos;/g, "'")
            .replace(/&lt;/g, '<')
            .replace(/&gt;/g, '>')
            .replace(/&amp;/g, '&');
    }
    return decoded;
}

/**
 * The words of a timed-text document, as running text. Both of YouTube's XML
 * shapes: `<text start dur>` lines, and the newer `<p t d><s>word</s></p>`.
 */
export function captionText(xml: string): string {
    const pieces = [...xml.matchAll(/<(text|p)\b[^>]*>([\s\S]*?)<\/\1>/gi)].map((match) =>
        decodeEntities(match[2].replace(/<[^>]+>/g, '')).replace(/\s+/g, ' ').trim()
    );
    return pieces
        .filter((piece) => piece && !/^\[(musik|music|applaus|applause|lachen|laughter)\]$/i.test(piece))
        .join(' ')
        .replace(/\s+/g, ' ')
        .trim();
}
