-- The starting stock's German further names written as German writes them ("Lauchzwiebel", "gelbe Zwiebel"):
-- the card tells a German name from an English one by its capitals (admin → Zutaten).
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'apfelsine', 'Apfelsine') WHERE 'apfelsine' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'babyspinat', 'Babyspinat') WHERE 'babyspinat' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'blattspinat', 'Blattspinat') WHERE 'blattspinat' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'cocktailtomate', 'Cocktailtomate') WHERE 'cocktailtomate' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'erbse', 'Erbse') WHERE 'erbse' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'fester tofu', 'fester Tofu') WHERE 'fester tofu' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'fischsoße', 'Fischsoße') WHERE 'fischsoße' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'frischer ingwer', 'frischer Ingwer') WHERE 'frischer ingwer' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'frischhefe', 'Frischhefe') WHERE 'frischhefe' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'gehackte tomaten', 'gehackte Tomaten') WHERE 'gehackte tomaten' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'gelbe rübe', 'gelbe Rübe') WHERE 'gelbe rübe' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'gelbe zwiebel', 'gelbe Zwiebel') WHERE 'gelbe zwiebel' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'gemüsebrühe', 'Gemüsebrühe') WHERE 'gemüsebrühe' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'geriebener parmesan', 'geriebener Parmesan') WHERE 'geriebener parmesan' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'geräuchertes paprikapulver', 'geräuchertes Paprikapulver') WHERE 'geräuchertes paprikapulver' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'geröstetes sesamöl', 'geröstetes Sesamöl') WHERE 'geröstetes sesamöl' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'glatte petersilie', 'glatte Petersilie') WHERE 'glatte petersilie' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'griechischer joghurt', 'griechischer Joghurt') WHERE 'griechischer joghurt' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'grüne bohne', 'grüne Bohne') WHERE 'grüne bohne' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'helle sojasauce', 'helle Sojasauce') WHERE 'helle sojasauce' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'hähnchenbrustfilet', 'Hähnchenbrustfilet') WHERE 'hähnchenbrustfilet' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'hühnerbrust', 'Hühnerbrust') WHERE 'hühnerbrust' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'hühnerbrühe', 'Hühnerbrühe') WHERE 'hühnerbrühe' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'ingwerwurzel', 'Ingwerwurzel') WHERE 'ingwerwurzel' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'kartoffelstärke', 'Kartoffelstärke') WHERE 'kartoffelstärke' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'kichererbse', 'Kichererbse') WHERE 'kichererbse' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'knoblauchzehe', 'Knoblauchzehe') WHERE 'knoblauchzehe' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'kopfsalat', 'Kopfsalat') WHERE 'kopfsalat' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'koriandergrün', 'Koriandergrün') WHERE 'koriandergrün' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'lauchzwiebel', 'Lauchzwiebel') WHERE 'lauchzwiebel' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'linse', 'Linse') WHERE 'linse' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'maiskolben', 'Maiskolben') WHERE 'maiskolben' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'maisstärke', 'Maisstärke') WHERE 'maisstärke' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'meersalz', 'Meersalz') WHERE 'meersalz' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'mohrrübe', 'Mohrrübe') WHERE 'mohrrübe' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'möhre', 'Möhre') WHERE 'möhre' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'natives olivenöl', 'natives Olivenöl') WHERE 'natives olivenöl' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'naturjoghurt', 'Naturjoghurt') WHERE 'naturjoghurt' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'paniermehl', 'Paniermehl') WHERE 'paniermehl' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'paprika edelsüß', 'Paprika edelsüß') WHERE 'paprika edelsüß' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'paprikaschote', 'Paprikaschote') WHERE 'paprikaschote' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'peperoni', 'Peperoni') WHERE 'peperoni' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'pflanzenöl', 'Pflanzenöl') WHERE 'pflanzenöl' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'pilz', 'Pilz') WHERE 'pilz' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'porree', 'Porree') WHERE 'porree' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'prinzessbohne', 'Prinzessbohne') WHERE 'prinzessbohne' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'rapsöl', 'Rapsöl') WHERE 'rapsöl' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'rinderhack', 'Rinderhack') WHERE 'rinderhack' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'rote paprikaschote', 'rote Paprikaschote') WHERE 'rote paprikaschote' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'salatgurke', 'Salatgurke') WHERE 'salatgurke' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'schafskäse', 'Schafskäse') WHERE 'schafskäse' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'schlagsahne', 'Schlagsahne') WHERE 'schlagsahne' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'schmand', 'Schmand') WHERE 'schmand' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'schwarzer pfeffer', 'schwarzer Pfeffer') WHERE 'schwarzer pfeffer' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'sesamsamen', 'Sesamsamen') WHERE 'sesamsamen' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'sojasoße', 'Sojasoße') WHERE 'sojasoße' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'sonnenblumenöl', 'Sonnenblumenöl') WHERE 'sonnenblumenöl' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'stangensellerie', 'Stangensellerie') WHERE 'stangensellerie' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'stärke', 'Stärke') WHERE 'stärke' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'stückige tomaten', 'stückige Tomaten') WHERE 'stückige tomaten' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'thai-basilikum', 'Thai-Basilikum') WHERE 'thai-basilikum' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'trockenhefe', 'Trockenhefe') WHERE 'trockenhefe' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'ungesalzene butter', 'ungesalzene Butter') WHERE 'ungesalzene butter' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'vollmilch', 'Vollmilch') WHERE 'vollmilch' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'weizenmehl', 'Weizenmehl') WHERE 'weizenmehl' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'weizenmehl type 405', 'Weizenmehl Type 405') WHERE 'weizenmehl type 405' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'weißer zucker', 'weißer Zucker') WHERE 'weißer zucker' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'weißkohl', 'Weißkohl') WHERE 'weißkohl' = ANY("aliases");
UPDATE "IngredientItem" SET "aliases" = array_replace("aliases", 'zimtpulver', 'Zimtpulver') WHERE 'zimtpulver' = ANY("aliases");
