-- The cookbook's ingredients, once each, in both languages (lib/ingredientCatalog).
CREATE TABLE "IngredientItem" (
    "id" SERIAL NOT NULL,
    "de" TEXT NOT NULL DEFAULT '',
    "en" TEXT NOT NULL DEFAULT '',
    "aliases" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "keys" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "IngredientItem_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "IngredientItem_keys_idx" ON "IngredientItem" USING GIN ("keys");

ALTER TABLE "Ingredient" ADD COLUMN "itemId" INTEGER;
ALTER TABLE "Ingredient" ADD CONSTRAINT "Ingredient_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "IngredientItem"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE INDEX "Ingredient_itemId_idx" ON "Ingredient"("itemId");

ALTER TABLE "ShoppingItem" ADD COLUMN "itemId" INTEGER;
ALTER TABLE "ShoppingItem" ADD CONSTRAINT "ShoppingItem_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "IngredientItem"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- The common ingredients to start with (lib/ingredientNames). Every other
-- one is added the first time a recipe uses it.
INSERT INTO "IngredientItem" ("de", "en", "aliases", "keys", "updatedAt") VALUES
    ('Frühlingszwiebeln', 'spring onions', ARRAY['Frühlingszwiebel', 'spring onion', 'green onion', 'scallion', 'lauchzwiebel', 'salad onion']::TEXT[], ARRAY['frühlingszwiebel', 'spring onio', 'green onio', 'scallio', 'lauchzwiebel', 'salad onio']::TEXT[], CURRENT_TIMESTAMP),
    ('Zwiebeln', 'onions', ARRAY['Zwiebel', 'onion', 'yellow onion', 'gelbe zwiebel', 'brown onion']::TEXT[], ARRAY['zwiebel', 'onio', 'yellow onio', 'gelbe zwiebel', 'brown onio']::TEXT[], CURRENT_TIMESTAMP),
    ('rote Zwiebeln', 'red onions', ARRAY['rote Zwiebel', 'red onion']::TEXT[], ARRAY['rote zwiebel', 'red onio']::TEXT[], CURRENT_TIMESTAMP),
    ('Schalotten', 'shallots', ARRAY['Schalotte', 'shallot']::TEXT[], ARRAY['schalott', 'shallot']::TEXT[], CURRENT_TIMESTAMP),
    ('Knoblauch', 'garlic', ARRAY['knoblauchzehe', 'garlic clove', 'clove garlic', 'clove of garlic']::TEXT[], ARRAY['knoblauch', 'garlic', 'knoblauchzeh', 'garlic clov', 'clove garlic', 'clove of garlic']::TEXT[], CURRENT_TIMESTAMP),
    ('Ingwer', 'ginger', ARRAY['fresh ginger', 'ginger root', 'ingwerwurzel', 'frischer ingwer']::TEXT[], ARRAY['ingw', 'ging', 'fresh ging', 'ginger root', 'ingwerwurzel', 'frischer ingw']::TEXT[], CURRENT_TIMESTAMP),
    ('Lauch', 'leeks', ARRAY['leek', 'porree']::TEXT[], ARRAY['lauch', 'leek', 'porr']::TEXT[], CURRENT_TIMESTAMP),
    ('Karotten', 'carrots', ARRAY['Karotte', 'carrot', 'möhre', 'mohrrübe', 'gelbe rübe']::TEXT[], ARRAY['karott', 'carrot', 'möhr', 'mohrrüb', 'gelbe rueb']::TEXT[], CURRENT_TIMESTAMP),
    ('Kartoffeln', 'potatoes', ARRAY['Kartoffel', 'potato']::TEXT[], ARRAY['kartoffel', 'potato']::TEXT[], CURRENT_TIMESTAMP),
    ('Süßkartoffeln', 'sweet potatoes', ARRAY['Süßkartoffel', 'sweet potato']::TEXT[], ARRAY['süßkartoffel', 'sweet potato']::TEXT[], CURRENT_TIMESTAMP),
    ('Tomaten', 'tomatoes', ARRAY['Tomate', 'tomato']::TEXT[], ARRAY['tomat', 'tomato']::TEXT[], CURRENT_TIMESTAMP),
    ('Kirschtomaten', 'cherry tomatoes', ARRAY['Kirschtomate', 'cherry tomato', 'cocktailtomate']::TEXT[], ARRAY['kirschtomat', 'cherry tomato', 'cocktailtomat']::TEXT[], CURRENT_TIMESTAMP),
    ('Gurken', 'cucumbers', ARRAY['Gurke', 'cucumber', 'salatgurke']::TEXT[], ARRAY['gurk', 'cucumb', 'salatgurk']::TEXT[], CURRENT_TIMESTAMP),
    ('Zucchini', 'courgettes', ARRAY['courgette', 'zucchini', 'zucchino']::TEXT[], ARRAY['zucchini', 'courgett', 'zucchino']::TEXT[], CURRENT_TIMESTAMP),
    ('Auberginen', 'aubergines', ARRAY['Aubergine', 'aubergine', 'eggplant']::TEXT[], ARRAY['aubergi', 'eggplant']::TEXT[], CURRENT_TIMESTAMP),
    ('Paprika', 'bell peppers', ARRAY['bell pepper', 'paprikaschote', 'capsicum', 'sweet pepper']::TEXT[], ARRAY['paprika', 'bell pepp', 'paprikaschot', 'capsicum', 'sweet pepp']::TEXT[], CURRENT_TIMESTAMP),
    ('rote Paprika', 'red bell peppers', ARRAY['red bell pepper', 'red pepper', 'rote paprikaschote']::TEXT[], ARRAY['rote paprika', 'red bell pepp', 'red pepp', 'rote paprikaschot']::TEXT[], CURRENT_TIMESTAMP),
    ('Chilischoten', 'chilies', ARRAY['Chilischote', 'chili', 'chilli', 'chile', 'chili pepper', 'peperoni']::TEXT[], ARRAY['chilischot', 'chili', 'chilli', 'chil', 'chili pepp', 'peperoni']::TEXT[], CURRENT_TIMESTAMP),
    ('Champignons', 'mushrooms', ARRAY['Champignon', 'mushroom', 'pilz', 'button mushroom']::TEXT[], ARRAY['champigno', 'mushroom', 'pilz', 'button mushroom']::TEXT[], CURRENT_TIMESTAMP),
    ('Spinat', 'spinach', ARRAY['baby spinach', 'babyspinat', 'blattspinat']::TEXT[], ARRAY['spinat', 'spinach', 'baby spinach', 'babyspinat', 'blattspinat']::TEXT[], CURRENT_TIMESTAMP),
    ('Salat', 'lettuce', ARRAY['kopfsalat']::TEXT[], ARRAY['salat', 'lettuc', 'kopfsalat']::TEXT[], CURRENT_TIMESTAMP),
    ('Kohl', 'cabbage', ARRAY['weißkohl', 'white cabbage']::TEXT[], ARRAY['kohl', 'cabbag', 'weißkohl', 'white cabbag']::TEXT[], CURRENT_TIMESTAMP),
    ('Chinakohl', 'napa cabbage', ARRAY['chinese cabbage', 'nappa cabbage']::TEXT[], ARRAY['chinakohl', 'napa cabbag', 'chinese cabbag', 'nappa cabbag']::TEXT[], CURRENT_TIMESTAMP),
    ('Brokkoli', 'broccoli', ARRAY[]::TEXT[], ARRAY['brokkoli', 'broccoli']::TEXT[], CURRENT_TIMESTAMP),
    ('Blumenkohl', 'cauliflower', ARRAY[]::TEXT[], ARRAY['blumenkohl', 'cauliflow']::TEXT[], CURRENT_TIMESTAMP),
    ('Staudensellerie', 'celery', ARRAY['stangensellerie', 'celery stalk']::TEXT[], ARRAY['staudenselleri', 'celery', 'stangenselleri', 'celery stalk']::TEXT[], CURRENT_TIMESTAMP),
    ('Kürbisse', 'pumpkins', ARRAY['Kürbis', 'pumpkin', 'squash', 'hokkaido']::TEXT[], ARRAY['kürbi', 'pumpki', 'squash', 'hokkaido']::TEXT[], CURRENT_TIMESTAMP),
    ('Mais', 'corn', ARRAY['sweetcorn', 'maiskolben']::TEXT[], ARRAY['mais', 'corn', 'sweetcor', 'maiskolb']::TEXT[], CURRENT_TIMESTAMP),
    ('Erbsen', 'peas', ARRAY['erbse', 'pea', 'green pea']::TEXT[], ARRAY['erbs', 'peas', 'pea', 'green pea']::TEXT[], CURRENT_TIMESTAMP),
    ('grüne Bohnen', 'green beans', ARRAY['green bean', 'grüne bohne', 'prinzessbohne', 'string bean']::TEXT[], ARRAY['grüne bohn', 'green bean', 'prinzessboh', 'string bean']::TEXT[], CURRENT_TIMESTAMP),
    ('Avocados', 'avocados', ARRAY['Avocado', 'avocado']::TEXT[], ARRAY['avocado']::TEXT[], CURRENT_TIMESTAMP),
    ('Zitronen', 'lemons', ARRAY['Zitrone', 'lemon']::TEXT[], ARRAY['zitro', 'lemo']::TEXT[], CURRENT_TIMESTAMP),
    ('Limetten', 'limes', ARRAY['Limette', 'lime']::TEXT[], ARRAY['limett', 'lime']::TEXT[], CURRENT_TIMESTAMP),
    ('Orangen', 'oranges', ARRAY['Orange', 'orange', 'apfelsine']::TEXT[], ARRAY['orang', 'apfelsi']::TEXT[], CURRENT_TIMESTAMP),
    ('Äpfel', 'apples', ARRAY['Apfel', 'apple']::TEXT[], ARRAY['apfel', 'äpfel', 'appl']::TEXT[], CURRENT_TIMESTAMP),
    ('Bananen', 'bananas', ARRAY['Banane', 'banana']::TEXT[], ARRAY['bana', 'banana']::TEXT[], CURRENT_TIMESTAMP),
    ('Petersilie', 'parsley', ARRAY['glatte petersilie', 'flat-leaf parsley', 'italian parsley']::TEXT[], ARRAY['petersili', 'parsley', 'glatte petersili', 'flat-leaf parsley', 'italian parsley']::TEXT[], CURRENT_TIMESTAMP),
    ('Basilikum', 'basil', ARRAY['thai basil', 'thai-basilikum']::TEXT[], ARRAY['basilikum', 'basil', 'thai basil', 'thai-basilikum']::TEXT[], CURRENT_TIMESTAMP),
    ('Koriander', 'coriander', ARRAY['cilantro', 'koriandergrün', 'fresh coriander']::TEXT[], ARRAY['koriand', 'coriand', 'cilantro', 'koriandergrü', 'fresh coriand']::TEXT[], CURRENT_TIMESTAMP),
    ('Minze', 'mint', ARRAY[]::TEXT[], ARRAY['minz', 'mint']::TEXT[], CURRENT_TIMESTAMP),
    ('Dill', 'dill', ARRAY[]::TEXT[], ARRAY['dill']::TEXT[], CURRENT_TIMESTAMP),
    ('Schnittlauch', 'chives', ARRAY['chive']::TEXT[], ARRAY['schnittlauch', 'chiv']::TEXT[], CURRENT_TIMESTAMP),
    ('Rosmarin', 'rosemary', ARRAY[]::TEXT[], ARRAY['rosmari', 'rosemary']::TEXT[], CURRENT_TIMESTAMP),
    ('Thymian', 'thyme', ARRAY[]::TEXT[], ARRAY['thymia', 'thym']::TEXT[], CURRENT_TIMESTAMP),
    ('Eier', 'eggs', ARRAY['Ei', 'egg', 'large egg']::TEXT[], ARRAY['ei', 'egg', 'large egg']::TEXT[], CURRENT_TIMESTAMP),
    ('Butter', 'butter', ARRAY['unsalted butter', 'ungesalzene butter']::TEXT[], ARRAY['butt', 'unsalted butt', 'ungesalzene butt']::TEXT[], CURRENT_TIMESTAMP),
    ('Milch', 'milk', ARRAY['vollmilch', 'whole milk']::TEXT[], ARRAY['milch', 'milk', 'vollmilch', 'whole milk']::TEXT[], CURRENT_TIMESTAMP),
    ('Sahne', 'cream', ARRAY['schlagsahne', 'heavy cream', 'double cream', 'whipping cream']::TEXT[], ARRAY['sahn', 'cream', 'schlagsah', 'heavy cream', 'double cream', 'whipping cream']::TEXT[], CURRENT_TIMESTAMP),
    ('saure Sahne', 'sour cream', ARRAY['schmand']::TEXT[], ARRAY['saure sahn', 'sour cream', 'schmand']::TEXT[], CURRENT_TIMESTAMP),
    ('Crème fraîche', 'crème fraîche', ARRAY['creme fraiche']::TEXT[], ARRAY['crème fraîch', 'creme fraich']::TEXT[], CURRENT_TIMESTAMP),
    ('Joghurt', 'yogurt', ARRAY['yoghurt', 'naturjoghurt', 'greek yogurt', 'griechischer joghurt']::TEXT[], ARRAY['joghurt', 'yogurt', 'yoghurt', 'naturjoghurt', 'greek yogurt', 'griechischer joghurt']::TEXT[], CURRENT_TIMESTAMP),
    ('Parmesan', 'parmesan', ARRAY['parmigiano', 'parmigiano reggiano', 'grated parmesan', 'geriebener parmesan']::TEXT[], ARRAY['parmesa', 'parmigiano', 'parmigiano reggiano', 'grated parmesa', 'geriebener parmesa']::TEXT[], CURRENT_TIMESTAMP),
    ('Mozzarella', 'mozzarella', ARRAY[]::TEXT[], ARRAY['mozzarella']::TEXT[], CURRENT_TIMESTAMP),
    ('Feta', 'feta', ARRAY['schafskäse']::TEXT[], ARRAY['feta', 'schafskä']::TEXT[], CURRENT_TIMESTAMP),
    ('Mehl', 'flour', ARRAY['all-purpose flour', 'plain flour', 'weizenmehl', 'weizenmehl type 405']::TEXT[], ARRAY['mehl', 'flour', 'all-purpose flour', 'plain flour', 'weizenmehl', 'weizenmehl type 405']::TEXT[], CURRENT_TIMESTAMP),
    ('Zucker', 'sugar', ARRAY['white sugar', 'granulated sugar', 'weißer zucker']::TEXT[], ARRAY['zuck', 'sugar', 'white sugar', 'granulated sugar', 'weißer zuck']::TEXT[], CURRENT_TIMESTAMP),
    ('brauner Zucker', 'brown sugar', ARRAY[]::TEXT[], ARRAY['brauner zuck', 'brown sugar']::TEXT[], CURRENT_TIMESTAMP),
    ('Puderzucker', 'icing sugar', ARRAY['powdered sugar', 'confectioners'' sugar']::TEXT[], ARRAY['puderzuck', 'icing sugar', 'powdered sugar', 'confectioners sugar']::TEXT[], CURRENT_TIMESTAMP),
    ('Salz', 'salt', ARRAY['sea salt', 'meersalz', 'kosher salt']::TEXT[], ARRAY['salz', 'salt', 'sea salt', 'meersalz', 'kosher salt']::TEXT[], CURRENT_TIMESTAMP),
    ('Pfeffer', 'black pepper', ARRAY['pepper', 'schwarzer pfeffer', 'ground black pepper']::TEXT[], ARRAY['pfeff', 'black pepp', 'pepp', 'schwarzer pfeff', 'ground black pepp']::TEXT[], CURRENT_TIMESTAMP),
    ('Olivenöl', 'olive oil', ARRAY['extra virgin olive oil', 'natives olivenöl']::TEXT[], ARRAY['olivenöl', 'olive oil', 'extra virgin olive oil', 'natives olivenöl']::TEXT[], CURRENT_TIMESTAMP),
    ('neutrales Öl', 'neutral oil', ARRAY['vegetable oil', 'pflanzenöl', 'sonnenblumenöl', 'sunflower oil', 'rapsöl', 'canola oil', 'rapeseed oil']::TEXT[], ARRAY['neutrales öl', 'neutral oil', 'vegetable oil', 'pflanzenöl', 'sonnenblumenöl', 'sunflower oil', 'rapsöl', 'canola oil', 'rapeseed oil']::TEXT[], CURRENT_TIMESTAMP),
    ('Sesamöl', 'sesame oil', ARRAY['toasted sesame oil', 'geröstetes sesamöl']::TEXT[], ARRAY['sesamöl', 'sesame oil', 'toasted sesame oil', 'geröstetes sesamöl']::TEXT[], CURRENT_TIMESTAMP),
    ('Sojasauce', 'soy sauce', ARRAY['sojasoße', 'shoyu', 'light soy sauce', 'helle sojasauce']::TEXT[], ARRAY['sojasauc', 'soy sauc', 'sojasoß', 'shoyu', 'light soy sauc', 'helle sojasauc']::TEXT[], CURRENT_TIMESTAMP),
    ('Fischsauce', 'fish sauce', ARRAY['fischsoße']::TEXT[], ARRAY['fischsauc', 'fish sauc', 'fischsoß']::TEXT[], CURRENT_TIMESTAMP),
    ('Reisessig', 'rice vinegar', ARRAY['rice wine vinegar']::TEXT[], ARRAY['reisessig', 'rice vinegar', 'rice wine vinegar']::TEXT[], CURRENT_TIMESTAMP),
    ('Essig', 'vinegar', ARRAY[]::TEXT[], ARRAY['essig', 'vinegar']::TEXT[], CURRENT_TIMESTAMP),
    ('Mirin', 'mirin', ARRAY[]::TEXT[], ARRAY['miri']::TEXT[], CURRENT_TIMESTAMP),
    ('Honig', 'honey', ARRAY[]::TEXT[], ARRAY['honig', 'honey']::TEXT[], CURRENT_TIMESTAMP),
    ('Senf', 'mustard', ARRAY[]::TEXT[], ARRAY['senf', 'mustard']::TEXT[], CURRENT_TIMESTAMP),
    ('Tomatenmark', 'tomato paste', ARRAY['tomato purée']::TEXT[], ARRAY['tomatenmark', 'tomato past', 'tomato puré']::TEXT[], CURRENT_TIMESTAMP),
    ('Dosentomaten', 'canned tomatoes', ARRAY['tinned tomatoes', 'stückige tomaten', 'gehackte tomaten', 'chopped tomatoes', 'diced tomatoes']::TEXT[], ARRAY['dosentomat', 'canned tomato', 'tinned tomato', 'stückige tomat', 'gehackte tomat', 'chopped tomato', 'diced tomato']::TEXT[], CURRENT_TIMESTAMP),
    ('Kokosmilch', 'coconut milk', ARRAY[]::TEXT[], ARRAY['kokosmilch', 'coconut milk']::TEXT[], CURRENT_TIMESTAMP),
    ('Brühe', 'stock', ARRAY['broth', 'gemüsebrühe', 'vegetable stock', 'vegetable broth', 'hühnerbrühe', 'chicken stock', 'chicken broth']::TEXT[], ARRAY['brüh', 'stock', 'broth', 'gemüsebrüh', 'vegetable stock', 'vegetable broth', 'hühnerbrüh', 'chicken stock', 'chicken broth']::TEXT[], CURRENT_TIMESTAMP),
    ('Reis', 'rice', ARRAY[]::TEXT[], ARRAY['reis', 'rice']::TEXT[], CURRENT_TIMESTAMP),
    ('Jasminreis', 'jasmine rice', ARRAY[]::TEXT[], ARRAY['jasminrei', 'jasmine rice']::TEXT[], CURRENT_TIMESTAMP),
    ('Nudeln', 'pasta', ARRAY[]::TEXT[], ARRAY['nudel', 'pasta']::TEXT[], CURRENT_TIMESTAMP),
    ('Spaghetti', 'spaghetti', ARRAY[]::TEXT[], ARRAY['spaghetti']::TEXT[], CURRENT_TIMESTAMP),
    ('Semmelbrösel', 'breadcrumbs', ARRAY['paniermehl', 'panko', 'bread crumbs']::TEXT[], ARRAY['semmelbrösel', 'breadcrumb', 'paniermehl', 'panko', 'bread crumb']::TEXT[], CURRENT_TIMESTAMP),
    ('Speisestärke', 'cornstarch', ARRAY['cornflour', 'maisstärke', 'stärke', 'potato starch', 'kartoffelstärke']::TEXT[], ARRAY['speisestärk', 'cornstarch', 'cornflour', 'maisstärk', 'stärk', 'potato starch', 'kartoffelstärk']::TEXT[], CURRENT_TIMESTAMP),
    ('Backpulver', 'baking powder', ARRAY[]::TEXT[], ARRAY['backpulv', 'baking powd']::TEXT[], CURRENT_TIMESTAMP),
    ('Hefe', 'yeast', ARRAY['trockenhefe', 'dry yeast', 'frischhefe']::TEXT[], ARRAY['hefe', 'yeast', 'trockenhef', 'dry yeast', 'frischhef']::TEXT[], CURRENT_TIMESTAMP),
    ('Hähnchenbrust', 'chicken breasts', ARRAY['chicken breast', 'hühnerbrust', 'hähnchenbrustfilet']::TEXT[], ARRAY['hähnchenbrust', 'chicken breast', 'hühnerbrust', 'hähnchenbrustfilet']::TEXT[], CURRENT_TIMESTAMP),
    ('Rinderhackfleisch', 'ground beef', ARRAY['minced beef', 'beef mince', 'rinderhack']::TEXT[], ARRAY['rinderhackfleisch', 'ground beef', 'minced beef', 'beef minc', 'rinderhack']::TEXT[], CURRENT_TIMESTAMP),
    ('Tofu', 'tofu', ARRAY['firm tofu', 'fester tofu']::TEXT[], ARRAY['tofu', 'firm tofu', 'fester tofu']::TEXT[], CURRENT_TIMESTAMP),
    ('Seidentofu', 'silken tofu', ARRAY[]::TEXT[], ARRAY['seidentofu', 'silken tofu']::TEXT[], CURRENT_TIMESTAMP),
    ('Kichererbsen', 'chickpeas', ARRAY['chickpea', 'kichererbse', 'garbanzo bean']::TEXT[], ARRAY['kichererb', 'chickpea', 'garbanzo bean']::TEXT[], CURRENT_TIMESTAMP),
    ('Linsen', 'lentils', ARRAY['lentil', 'linse']::TEXT[], ARRAY['lins', 'lentil']::TEXT[], CURRENT_TIMESTAMP),
    ('Zimt', 'cinnamon', ARRAY['ground cinnamon', 'zimtpulver']::TEXT[], ARRAY['zimt', 'cinnamo', 'ground cinnamo', 'zimtpulv']::TEXT[], CURRENT_TIMESTAMP),
    ('Kreuzkümmel', 'cumin', ARRAY['ground cumin', 'cumin seed']::TEXT[], ARRAY['kreuzkümmel', 'cumi', 'ground cumi', 'cumin seed']::TEXT[], CURRENT_TIMESTAMP),
    ('Paprikapulver', 'paprika', ARRAY['sweet paprika', 'smoked paprika', 'paprika edelsüß', 'geräuchertes paprikapulver']::TEXT[], ARRAY['paprikapulv', 'paprika', 'sweet paprika', 'smoked paprika', 'paprika edelsu', 'geräuchertes paprikapulv']::TEXT[], CURRENT_TIMESTAMP),
    ('Chiliflocken', 'chili flakes', ARRAY['red pepper flakes', 'chilli flakes', 'gochugaru']::TEXT[], ARRAY['chiliflock', 'chili flak', 'red pepper flak', 'chilli flak', 'gochugaru']::TEXT[], CURRENT_TIMESTAMP),
    ('Sesam', 'sesame seeds', ARRAY['sesame seed', 'sesamsamen', 'sesame']::TEXT[], ARRAY['sesam', 'sesame seed', 'sesamsam']::TEXT[], CURRENT_TIMESTAMP),
    ('Wasser', 'water', ARRAY[]::TEXT[], ARRAY['wass', 'water']::TEXT[], CURRENT_TIMESTAMP)
;
